ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views as users_views
from django.contrib.auth import views as auth_views
from cart import views as cart_views
from order import views as order_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users\login.html'), name='login'),
    path('register/', users_views.register, name='register'),
    path('profile/', users_views.profile, name = "profile"),
    path('logout/', users_views.logout_view, name='logout'),
    path('cart/', cart_views.cart_detail, name='cart_detail'),
    path('add-to-cart/<int:product_id>/', cart_views.add_to_cart, name='add_to_cart'), 
    path('remove-from-cart/<int:product_id>/', cart_views.remove_from_cart, name='remove_from_cart'),
    path('minus-from-cart/<int:product_id>/', cart_views.minus_from_cart, name= 'minus_from_cart'),
    path('edit-profile/', users_views.edit_profile, name='edit_profile'),
    path('orders/', order_views.order_detail, name='order_detail' ),
    path('checkout/', order_views.checkout, name='checkout'),
    path('checkout-item/<int:product_id>', order_views.checkout_item, name='checkout_item'),
    path('',include('home.urls')),

]
 

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name = "index"),
    path('<int:id>/', views.detail, name='detail'),
    path('<str:cat>/',views.category_view, name='category')
]

home/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    desc = models.TextField()
    discount_price = models.FloatField()
    category = models.CharField(max_length=200)
    image = models.CharField(max_length=300)

    def __str__(self) -> str:
        return self.name

home/views.py
from django.shortcuts import render
from django.core.paginator import Paginator 
from .models import Product
# Create your views here.

def index(request):
    products = Product.objects.all().order_by('name')
    paginator = Paginator(products,8)
    page = request.GET.get('page')
    products = paginator.get_page(page)
    search = request.GET.get('search_item')
    flag = False
    if search is not None and search != '':      
        products = Product.objects.filter(name__icontains = search) 
        flag = True
    return render(request, 'home/index.html', {"products":products, "search_flag":flag} )

def detail(request,id):
    product = Product.objects.get(id=id)
    return render(request, 'home/detail.html', {"product":product})


def category_view(request, cat):
    products = Product.objects.filter(category = cat).order_by('name')
    return render(request, 'home/category.html', {'products':products, "category":cat})

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<nav class="navbar sticky-top navbar-expand-md bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand text-white" href="{% url 'home:index' %}">
            <img src="{% static 'images/SI.jpg' %}" width="40" height="40" class="d-inline-block align-text-center rounded-circle"> ShopIt</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarTogglerDemo02">
            <form class="d-inline-flex mx-md-auto col-md-6 col-12 mt-2 mt-md-0" role="search">
                <input class="form-control me-2" type="search" name="search_item" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                  </svg></button>
            </form>
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Category
                </button>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'home:category' 'Books' %}">Books</a></li>
                  <li><a class="dropdown-item" href="{% url 'home:category' 'Electronics' %}">Electronics</a></li>
                  <li><a class="dropdown-item" href="{% url 'home:category' 'Home&Kitchen' %}">Home and Kitchen </a></li>
                </ul>
              </div>
            <ul class="navbar-nav mb-2 mb-lg-0  ms-auto">
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'cart_detail' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5M3.14 5l.5 2H5V5zM6 5v2h2V5zm3 0v2h2V5zm3 0v2h1.36l.5-2zm1.11 3H12v2h.61zM11 8H9v2h2zM8 8H6v2h2zM5 8H3.89l.5 2H5zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0m9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0"/>
                      </svg> Cart</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'order_detail' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-box-seam" viewBox="0 0 16 16">
                        <path d="M8.186 1.113a.5.5 0 0 0-.372 0L1.846 3.5l2.404.961L10.404 2zm3.564 1.426L5.596 5 8 5.961 14.154 3.5zm3.25 1.7-6.5 2.6v7.922l6.5-2.6V4.24zM7.5 14.762V6.838L1 4.239v7.923zM7.443.184a1.5 1.5 0 0 1 1.114 0l7.129 2.852A.5.5 0 0 1 16 3.5v8.662a1 1 0 0 1-.629.928l-7.185 2.874a.5.5 0 0 1-.372 0L.63 13.09a1 1 0 0 1-.63-.928V3.5a.5.5 0 0 1 .314-.464z"/>
                      </svg> Order</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'profile' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                        <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                        <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                      </svg> Account</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link text-white logout" href="{% url 'logout' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30"
                            height="30" fill="currentColor" class="bi bi-box-arrow-in-left " viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M10 3.5a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 1 1 0v2A1.5 1.5 0 0 1 9.5 14h-8A1.5 1.5 0 0 1 0 12.5v-9A1.5 1.5 0 0 1 1.5 2h8A1.5 1.5 0 0 1 11 3.5v2a.5.5 0 0 1-1 0z" />
                            <path fill-rule="evenodd"
                                d="M4.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H14.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708z" />
                        </svg> Log Out</a>
                    {% else %}
                    <a href="{% url 'login' %}" class="nav-link text-white"><svg xmlns="http://www.w3.org/2000/svg" width="30"
                            height="30" fill="currentColor" class="bi bi-box-arrow-in-right" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M6 3.5a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 0-1 0v2A1.5 1.5 0 0 0 6.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-8A1.5 1.5 0 0 0 5 3.5v2a.5.5 0 0 0 1 0z" />
                            <path fill-rule="evenodd"
                                d="M11.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H1.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708z" />
                        </svg> Log In</a>
                    {% endif %}
                </li>
            </ul>
            
        </div>
</nav>

{% block body %} 
{% endblock %}
<div class="container">
    <footer class="py-3 my-4">
      <ul class="nav justify-content-center  border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="{% url 'home:index' %}" class="nav-link px-2 text-body-secondary">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About us</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Customer Support</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQ's</a></li>
      </ul>
      {% now "Y" as current_year %}
      <p class="text-center text-body-secondary">© {{ current_year}} ShopIt, Inc</p>
    </footer>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
<script src="{% static 'app.js' %}"></script>
</body>

</html>

home/templates/home/category.html
{% extends 'home\base.html' %}
{% block title %} {{ category }} {% endblock %}
{% block body %}
<div class="container">
  <div class="row ">
    {% for item in products %}
    <div class="col-xl-3 col-md-6 d-flex justify-content-center">
    <div class="card my-5 " style="width: 18rem">
      <a href="{% url 'home:detail' item.id %}">
      <img
        src="{{item.image}}"
        class="card-img-top object-fit-scale border rounded"
        height="200px"
        alt="{{ item.name }}"
      />
      <div class="card-body">
        
        <h5 class="card-title">{{ item.name }}</h5>
        <p class="card-text">
          &#8377;{{ item.discount_price|floatformat:2 }} <del>&#8377;{{ item.price|floatformat:2 }}</del>
        </p></a>
        <a href="{% url 'add_to_cart' item.id %}" class="btn btn-primary">Add to Cart </a>
      </div>
    </div>
  </div>
    {% endfor %}
  </div>
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item {% if not products.has_previous %}disabled{% endif %}">
      <a class="page-link" href="{% if products.has_previous %}?page={{ products.previous_page_number }}{% else %}#{% endif %}">Previous</a>
    </li>    
    {% for num in products.paginator.page_range %}
    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
    {% endfor %}
    
    <li class="page-item {% if not products.has_next %} disabled {% endif %}">
      <a class="page-link" href="{% if products.has_next %}?page={{ products.next_page_number }}{% else %}#{% endif %}">Next</a>
    </li>

  </ul>
</nav>



{% endblock %}

home/templates/home/detail.html
{% extends 'home/base.html' %}

{% block title %}{{ product.name }}{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <h1>{{ product.name }}</h1>
        <hr>
        <div class="col-xl-8  d-flex justify-content-center  border-start border-end"><img src="{{product.image }}" class="object-fit-scale" height="500px"></div>
        <div class="col-xl-4">
        <h3>Description</h3>    
        <hr>
        <p>{{ product.desc }}</p>
        <hr>
        <h3>Price</h3>
        <h4>&#8377; {{ product.discount_price|floatformat:2 }}<br><del>&#8377; {{ product.price|floatformat:2 }}</del></h4>
        <a href="{% url 'add_to_cart' product.id %}" class="btn btn-primary px-5">Add to Cart</a>
        <a  href="{% url 'checkout_item' product.id %}" class="btn btn-primary px-5">Buy Now</a>
        
        </div>
    </div>
</div>




{{ product. }}
{% endblock %}

home/templates/home/index.html
{% extends 'home\base.html' %} 
{% load static %} 
{% block title %}ShopIt {%endblock %}
{% block body %}

{% if not search_flag %}
<div
  id="carouselExampleAutoplaying"
  class="carousel slide"
  data-bs-ride="carousel"
>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img
        src="{% static 'images/Fashion.png' %}"
        class="d-block w-100 object-fit-fill"
        height="350px"
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'images/electronics.png' %}"
        class="d-block w-100 object-fit-fill"
        height="350px"
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'images/books.png' %}"
        class="d-block w-100 object-fit-fill"
        height="350px"
      />
    </div>
    <div class="carousel-item">
      <img
        src="{% static 'images/kitchen.png' %}"
        class="d-block w-100 object-fit-fill"
        height="350px"
      />
    </div>
  </div>
  <button
    class="carousel-control-prev"
    type="button"
    data-bs-target="#carouselExampleAutoplaying"
    data-bs-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-bs-target="#carouselExampleAutoplaying"
    data-bs-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
{% else %}

{% endif %}
<div class="container">
  <div class="row ">
    {% for item in products %}
    <div class="col-xl-3 col-md-6 d-flex justify-content-center">
    <div class="card my-5 " style="width: 18rem">
      <a href="{% url 'home:detail' item.id %}">
      <img
        src="{{item.image}}"
        class="card-img-top object-fit-scale border rounded"
        height="200px"
        alt="{{ item.name }}"
      />
      <div class="card-body">
        <h5 class="card-title">{{ item.name }}</h5>
        <p class="card-text mb-3">
          &#8377;{{ item.discount_price|floatformat:2 }} <del>&#8377;{{ item.price|floatformat:2 }}</del>
        </p></a>
        <a href="{% url 'add_to_cart' item.id %}" class="btn btn-primary">Add to Cart </a>
      </div>
    </div>
  </div>
    {% endfor %}
  </div>
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item {% if not products.has_previous %}disabled{% endif %}">
      <a class="page-link" href="{% if products.has_previous %}?page={{ products.previous_page_number }}{% else %}#{% endif %}">Previous</a>
    </li>    
    {% for num in products.paginator.page_range %}
    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
    {% endfor %}
    
    <li class="page-item {% if not products.has_next %} disabled {% endif %}">
      <a class="page-link" href="{% if products.has_next %}?page={{ products.next_page_number }}{% else %}#{% endif %}">Next</a>
    </li>

  </ul>
</nav>
{% endblock %}